name: cat_girl_calculator
description: A retro pixel art cat girl calculator
publish_to: 'none'
version: 1.0.11+25

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sprites/pixel_v2/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_logo.jpg"
  adaptive_icon_background: "#F3F6F8"
  adaptive_icon_foreground: "assets/images/app_logo.jpg"
